"""add User, Subscription, RateSnapshot, SubscriptionTemplate models

Revision ID: 342f1b2eeb44
Revises: 
Create Date: 2026-05-12 13:57:39.394106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342f1b2eeb44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'captured_at', name='uq_rate_snapshot_pair_time')
    )
    with op.batch_alter_table('rate_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_rate_snapshot_pair_time', ['from_currency', 'to_currency', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_snapshots_from_currency'), ['from_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_snapshots_to_currency'), ['to_currency'], unique=False)

    op.create_table('subscription_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('plan_name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', 'country_code', 'plan_name', name='uq_template_service_country_plan')
    )
    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_templates_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_templates_service_name'), ['service_name'], unique=False)
        batch_op.create_index('ix_template_service_country', ['service_name', 'country_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('home_currency', sa.String(length=3), nullable=False),
    sa.Column('budget_kes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscription_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_template_service_country')
        batch_op.drop_index(batch_op.f('ix_subscription_templates_service_name'))
        batch_op.drop_index(batch_op.f('ix_subscription_templates_country_code'))
        batch_op.drop_index(batch_op.f('ix_subscription_templates_category'))

    op.drop_table('subscription_templates')
    with op.batch_alter_table('rate_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_snapshots_to_currency'))
        batch_op.drop_index(batch_op.f('ix_rate_snapshots_from_currency'))
        batch_op.drop_index(batch_op.f('ix_rate_snapshots_captured_at'))
        batch_op.drop_index('ix_rate_snapshot_pair_time')

    op.drop_table('rate_snapshots')
    # ### end Alembic commands ###
